fix(rescue_instance): added tests
deNBI/simplevm-client pull request #636
Opened 2024-11-13 06:58 UTC by qqmok

@dweinholz 

Try to fulfill the following points before the Pull Request is merged:

- [ ] The PR is reviewed by one of the team members.
- [ ] If a linting PR exists, it must be merged before this PR is allowed to be merged.
- [ ] If the PR is merged in the master then a release should be be made.
- [ ] If the new code is readable, if not it should be well commented

For releases only:

- [ ] If the review of this PR is approved and the PR is followed by a release then the .env file
  in the cloud-portal repo should also be updated.
- [ ] If you are making a release then please sum up the changes since the last release on the release page using the [clog](https://github.com/clog-tool/clog-cli) tool with `clog -F`

2024-11-13 15:09 UTC, dweinholz requested changes
When running the tests via:
python3-coverage run -m unittest discover -s .

All rescue tests are failing

2024-11-26 08:24 UTC, vktrrdk commented
One coverage test is still failing: 

2024-11-26 08:24:08,678 - Clearing traces of Playbook-VM for (openstack_id): c
....F..................2024-11-26 08:24:08 - [ERROR] - [/home/ubuntu/code/simplevm-client/simple_vm_client/util/thrift_converter.py:os_to_thrift_volume:74] - Exception on os_to_thrift_volume:
string indices must be integers
2024-11-26 08:24:08,855 - Exception on os_to_thrift_volume:
string indices must be integers
.......
======================================================================
FAIL: test_rescue_server (simple_vm_client.test_virtualmachinehandler.TestVirtualMachineHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/code/simplevm-client/simple_vm_client/test_virtualmachinehandler.py", line 168, in test_rescue_server
    self.handler.openstack_connector.rescue_server.assert_called_once_with(
  File "/usr/lib/python3.10/unittest/mock.py", line 941, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: rescue_server(openstack_id='vm_id')
Actual: rescue_server(openstack_id='vm_id', admin_pass=None, image_ref=None)

----------------------------------------------------------------------
Ran 306 tests in 3.103s

FAILED (failures=1)

2024-11-26 09:04 UTC, qqmok commented
> One coverage test is still failing:
> # 2024-11-26 08:24:08,678 - Clearing traces of Playbook-VM for (openstack_id): c
> ....F..................2024-11-26 08:24:08 - [ERROR] - [/home/ubuntu/code/simplevm-client/simple_vm_client/util/thrift_converter.py:os_to_thrift_volume:74] - Exception on os_to_thrift_volume:
> string indices must be integers
> 2024-11-26 08:24:08,855 - Exception on os_to_thrift_volume:
> string indices must be integers
> .......
> ## FAIL: test_rescue_server (simple_vm_client.test_virtualmachinehandler.TestVirtualMachineHandler)
> 
> Traceback (most recent call last): File "/home/ubuntu/code/simplevm-client/simple_vm_client/test_virtualmachinehandler.py", line 168, in test_rescue_server self.handler.openstack_connector.rescue_server.assert_called_once_with( File "/usr/lib/python3.10/unittest/mock.py", line 941, in assert_called_once_with return self.assert_called_with(*args, **kwargs) File "/usr/lib/python3.10/unittest/mock.py", line 929, in assert_called_with raise AssertionError(_error_message()) from cause AssertionError: expected call not found. Expected: rescue_server(openstack_id='vm_id') Actual: rescue_server(openstack_id='vm_id', admin_pass=None, image_ref=None)
> 
> Ran 306 tests in 3.103s
> 
> FAILED (failures=1)

The test is now updated and functioning

2024-12-03 08:18 UTC, dweinholz approved these changes

2024-12-03 08:18 UTC, merged